package: yform_flexible_content
version: "0.0.1-dev"
name: YForm flexible content
author: eaCe
supportpage: https://github.com/eace/yform_flexible_content

requires:
    redaxo: ^5.14.0
    php:
        version: '>=8.0'
    packages:
        yform/manager: '^4.0.2'

installer_ignore:
    - node_modules
    - .git
    - .gitignore
    - .github
    - package.json
    - yarn.lock
    - resources
    - .editorconfig
    - .eslintrc.js
    - .stylelintrc.js
    - vendor
