package: yform_flexible_content
version: "0.0.1-dev"
name: YForm flexible content
author: eaCe
supportpage: https://github.com/eace/yform_flexible_content

requires:
    redaxo: ^5.12.0
    php:
        version: '>=7.4'

page:
    title: translate:title
    perm: admin
    icon: rex-icon fa-space-shuttle
    subpages:
        settings: { title: translate:settings }
        gui_table: { title: translate:gui_table }
        gui_seeder: { title: translate:gui_seeder }

installer_ignore:
    - node_modules
    - .git
    - .gitignore
    - .github
    - package.json
    - yarn.lock
    - resources
    - .editorconfig
    - .eslintrc.js
    - .stylelintrc.js
    - vendor
